#!/usr/bin/env bash
# First-boot configuration for Raspberry Pi 5 — OFFLINE WiFi Access Point mode
# Run as root: sudo bash firstboot.sh
#
# After this script runs and the Pi reboots:
#   - Pi broadcasts WiFi SSID "AutoPilot-Setup" (WPA2)
#   - Pi has static IP 192.168.4.1 on wlan0
#   - DHCP serves 192.168.4.10–192.168.4.50 to connected devices
#   - mDNS works on the local AP network
#   - NO internet forwarding — pure local network

set -euo pipefail

AP_SSID="AutoPilot-Setup"
AP_PASS="autopilot"
AP_IP="192.168.4.1"
AP_CHANNEL=36
AP_COUNTRY="DE"
DHCP_RANGE_START="192.168.4.10"
DHCP_RANGE_END="192.168.4.50"
DHCP_LEASE="12h"
HOSTNAME="autopilot-pi"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "========================================="
echo "  Autopilot Pi — WiFi Access Point Setup"
echo "========================================="

# Ensure running as root
if [ "$EUID" -ne 0 ]; then
  echo "ERROR: Please run as root (sudo bash firstboot.sh)"
  exit 1
fi

# ─── Step 1: Hostname ───────────────────────────────────────────────
echo ""
echo "[1/8] Setting hostname to '${HOSTNAME}'..."
hostnamectl set-hostname "${HOSTNAME}"
sed -i "s/127\.0\.1\.1.*/127.0.1.1\t${HOSTNAME}/" /etc/hosts
echo "Hostname set to: $(hostname)"

# ─── Step 2: Install AP packages ────────────────────────────────────
echo ""
echo "[2/8] Installing hostapd + dnsmasq + avahi..."
apt-get update -y
apt-get install -y hostapd dnsmasq avahi-daemon avahi-utils libnss-mdns

# Stop services during configuration
systemctl stop hostapd 2>/dev/null || true
systemctl stop dnsmasq 2>/dev/null || true

# ─── Step 3: Create config directory ────────────────────────────────
echo ""
echo "[3/8] Creating /opt/autopilot/config/ directory..."
mkdir -p /opt/autopilot/config

# ─── Step 4: WiFi AP via NetworkManager (Pi OS Bookworm) ────────────
echo ""
echo "[4/8] Configuring WiFi Access Point..."

# Pi OS Bookworm uses NetworkManager by default — prefer nmcli AP mode
if command -v nmcli &>/dev/null; then
  echo "  Using NetworkManager (nmcli) for AP mode..."

  # Remove any existing AP connection
  nmcli con delete AutoPilot-AP 2>/dev/null || true

  # Create AP connection with nmcli
  nmcli con add type wifi ifname wlan0 con-name AutoPilot-AP \
    ssid "${AP_SSID}" autoconnect yes \
    wifi.mode ap wifi.band bg \
    wifi-sec.key-mgmt wpa-psk wifi-sec.psk "${AP_PASS}" \
    ipv4.method shared ipv4.addresses "${AP_IP}/24"

  echo "  NetworkManager AP configured: SSID=${AP_SSID}"

  # Disable hostapd since nmcli handles AP
  systemctl disable hostapd 2>/dev/null || true
  systemctl stop hostapd 2>/dev/null || true

  # Disable wpa_supplicant for wlan0 (nmcli manages it)
  systemctl disable wpa_supplicant@wlan0 2>/dev/null || true
  systemctl stop wpa_supplicant@wlan0 2>/dev/null || true

else
  echo "  NetworkManager not found — falling back to hostapd..."

  # ─── Fallback: hostapd + dhcpcd (legacy Pi OS) ─────────────────
  # Disable wpa_supplicant on wlan0
  if [ -f /etc/wpa_supplicant/wpa_supplicant.conf ]; then
    cp /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf.bak
  fi
  systemctl disable wpa_supplicant@wlan0 2>/dev/null || true
  systemctl stop wpa_supplicant@wlan0 2>/dev/null || true

  # Static IP for wlan0 via dhcpcd
  if [ -f /etc/dhcpcd.conf ]; then
    sed -i '/# autopilot-ap wlan0/,/^$/d' /etc/dhcpcd.conf
    cat >> /etc/dhcpcd.conf << EOF

# autopilot-ap wlan0 — static IP for access point
interface wlan0
    static ip_address=${AP_IP}/24
    nohook wpa_supplicant
EOF
  else
    cat > /etc/network/interfaces.d/wlan0 << EOF
auto wlan0
iface wlan0 inet static
    address ${AP_IP}
    netmask 255.255.255.0
EOF
  fi

  # hostapd configuration
  if [ -f "${SCRIPT_DIR}/hostapd.conf" ]; then
    cp "${SCRIPT_DIR}/hostapd.conf" /etc/hostapd/hostapd.conf
  else
    cat > /etc/hostapd/hostapd.conf << EOF
# AutoPilot — WiFi Access Point Configuration
# Generated by firstboot.sh

interface=wlan0
driver=nl80211

# Network
ssid=${AP_SSID}
country_code=${AP_COUNTRY}

# 5GHz 802.11ac
hw_mode=a
channel=${AP_CHANNEL}
ieee80211n=1
ieee80211ac=1
wmm_enabled=1

# WPA2 security
auth_algs=1
wpa=2
wpa_passphrase=${AP_PASS}
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

# Performance
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][DSSS_CCK-40]
vht_capab=[SHORT-GI-80]
vht_oper_chwidth=0
vht_oper_centr_freq_seg0_idx=38

# Logging
logger_syslog=-1
logger_syslog_level=2
logger_stdout=-1
logger_stdout_level=2
EOF
  fi

  # Point hostapd to our config
  mkdir -p /etc/hostapd
  echo 'DAEMON_CONF="/etc/hostapd/hostapd.conf"' > /etc/default/hostapd

  # Unmask hostapd (it's masked by default on Raspberry Pi OS)
  systemctl unmask hostapd
  systemctl enable hostapd
fi

# ─── Step 4b: Ethernet direct connection to Windows PC ────────────────
echo ""
echo "[4b/9] Configuring Ethernet bridge to PC..."
# Configure eth0 with static IP for direct PC connection
# Haupt-Pi = 192.168.5.1, Windows PC = 192.168.5.2
nmcli con delete PC-Direct 2>/dev/null || true
nmcli con add type ethernet ifname eth0 con-name PC-Direct \
    ipv4.method manual ipv4.addresses 192.168.5.1/24 \
    autoconnect yes

echo "Ethernet bridge configured: Pi=192.168.5.1, PC should be 192.168.5.2"

# ─── Step 5: dnsmasq configuration ──────────────────────────────────
echo ""
echo "[5/9] Configuring dnsmasq (DHCP: ${DHCP_RANGE_START}–${DHCP_RANGE_END})..."
# Back up original dnsmasq config
if [ -f /etc/dnsmasq.conf ] && [ ! -f /etc/dnsmasq.conf.orig ]; then
  mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig
fi

if [ -f "${SCRIPT_DIR}/dnsmasq.conf" ]; then
  cp "${SCRIPT_DIR}/dnsmasq.conf" /etc/dnsmasq.conf
else
  cat > /etc/dnsmasq.conf << EOF
# AutoPilot — DHCP + DNS for WiFi AP
# Generated by firstboot.sh

# Only listen on wlan0 (AP interface)
interface=wlan0
bind-interfaces

# DHCP range
dhcp-range=${DHCP_RANGE_START},${DHCP_RANGE_END},255.255.255.0,${DHCP_LEASE}

# Gateway (this Pi)
dhcp-option=3,${AP_IP}

# DNS — point to this Pi (dnsmasq handles local DNS)
dhcp-option=6,${AP_IP}

# Local domain
domain=autopilot.local
local=/autopilot.local/

# Static hostname mapping
address=/autopilot-pi.local/${AP_IP}
address=/autopilot.local/${AP_IP}

# Logging
log-queries
log-dhcp
log-facility=/var/log/dnsmasq.log
EOF
fi

# ─── Step 6: Avahi / mDNS ───────────────────────────────────────────
echo ""
echo "[6/9] Configuring mDNS (Avahi) for AP network..."
cat > /etc/avahi/avahi-daemon.conf << 'EOF'
[server]
host-name=autopilot-pi
domain-name=local
use-ipv4=yes
use-ipv6=yes
allow-interfaces=wlan0,eth0

[wide-area]
enable-wide-area=no

[publish]
publish-addresses=yes
publish-hinfo=yes
publish-workstation=no
publish-domain=yes

[reflector]
enable-reflector=no

[rlimits]
rlimit-core=0
rlimit-data=4194304
rlimit-fsize=0
rlimit-nofile=768
rlimit-stack=4194304
rlimit-nproc=3
EOF

# ─── Step 7: Enable services ────────────────────────────────────────
echo ""
echo "[7/9] Enabling services for next boot..."
systemctl enable dnsmasq
systemctl enable avahi-daemon

# ─── Step 8: Firewall + network ─────────────────────────────────────
echo ""
echo "[8/9] Configuring firewall and network..."
if command -v ufw &>/dev/null; then
  ufw allow 80/tcp comment "Nginx HTTP"
  ufw allow 4800/tcp comment "Autopilot iPad app"
  ufw allow 4801/tcp comment "Autopilot camera server"
  ufw allow 4804/tcp comment "Autopilot setup portal"
  ufw allow 53/udp comment "DNS (dnsmasq)"
  ufw allow 67/udp comment "DHCP (dnsmasq)"
  ufw allow 5353/udp comment "mDNS/Avahi"
fi

# Ensure NO IP forwarding (pure local network)
echo 0 > /proc/sys/net/ipv4/ip_forward
sed -i 's/^net.ipv4.ip_forward=1/net.ipv4.ip_forward=0/' /etc/sysctl.conf 2>/dev/null || true
if ! grep -q "net.ipv4.ip_forward" /etc/sysctl.conf; then
  echo "net.ipv4.ip_forward=0" >> /etc/sysctl.conf
fi

echo ""
echo "========================================="
echo "  WiFi Access Point Configuration Done!"
echo "========================================="
echo ""
echo "  SSID:          ${AP_SSID}"
echo "  Password:      ${AP_PASS}"
echo "  Pi IP:         ${AP_IP}"
echo "  DHCP range:    ${DHCP_RANGE_START} – ${DHCP_RANGE_END}"
echo "  Internet:      NONE (offline local network)"
echo ""
echo "  Ethernet:      eth0 → 192.168.5.1 (PC at 192.168.5.2)"
echo "  mDNS:          autopilot-pi.local"
echo "  Services:      Nginx on port 80 (after setup.sh)"
echo ""
echo "  >>> Run setup.sh next, then reboot: sudo reboot <<<"
echo ""
